---
title: "MA_Dataextraction"
author: "Johanna M Groening"
date: "2023-03-08"
output: html_document
---


```{r}
library(readxl)
library(tidyverse)
library(writexl)
library(ggplot2)
library(dplyr)
```





```{r}
# Strings auf 4 Wörter kürzen
library(ggplot2)
library(dplyr)
library(stringr)

# Strings auf 4 Wörter kürzen
df_prosp_short <- df_prosp %>%
  mutate(`Cannabis Level of use` = word(`Cannabis Level of use`, 1, 4)) 

# Häufigste Variablennamen auswählen
top_var_names <- df_prosp_short %>%
  count(`Cannabis Level of use`) %>%
  arrange(desc(n)) %>%
  slice_head(n = 5) %>%
  pull(`Cannabis Level of use`)

# Filtern des DataFrames basierend auf den häufigsten Variablennamen
df_filtered <- df_prosp_short %>%
  filter(`Cannabis Level of use` %in% top_var_names)

# Balkendiagramm der häufigsten Variablennamen
ggplot(df_filtered, aes(x = `Cannabis Level of use`)) +
  geom_bar(fill = "steelblue", position = "dodge", width = 0.7) +
  labs(x = "Cannabis Level of Use", y = "Count") +
  ggtitle("Cannabis Level of Use Distribution (Top Variables)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")


```

```{r}
library(ggplot2)
library(dplyr)
library(stringr)

# Strings auf 4 Wörter kürzen
df_prosp_short <- df_prosp %>%
  mutate(`Cannabis Level of use` = word(`Cannabis Level of use`, 1, 4)) 

# Balkendiagramm aller Variablen
ggplot(df_prosp_short, aes(x = `Cannabis Level of use`)) +
  geom_bar(fill = "steelblue", position = "dodge", width = 0.7) +
  labs(x = "Cannabis Level of Use", y = "Count") +
  ggtitle("Cannabis Level of Use Distribution") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")
```


```{r}
# Strings auf 4 Wörter kürzen
df_prosp_short <- df_prosp %>%
  mutate(Outcome = word(Outcome, 1, 4))

# Balkendiagramm der Variable "Outcome"
ggplot(df_prosp_short, aes(x = Outcome)) +
  geom_bar(fill = "steelblue", position = "dodge", width = 0.7) +
  labs(x = "Outcome", y = "Count") +
  ggtitle("Outcome Distribution") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")
```


```{r}
# Strings auf 4 Wörter kürzen
df_prosp_short <- df_prosp %>%
  mutate(`Outcome Measure` = word(`Outcome Measure`, 1, 4))

# Balkendiagramm der Variable "Outcome Measure"
ggplot(df_prosp_short, aes(x = `Outcome Measure`)) +
  geom_bar(fill = "steelblue", position = "dodge", width = 0.7) +
  labs(x = "Outcome Measure", y = "Count") +
  ggtitle("Outcome Measure Distribution") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = "none")
```




```{r}

df_prosp$Outcome_Measure_Truncated <- ifelse(nchar(df_prosp$`Outcome Measure`) > 4, word(df_prosp$`Outcome Measure`, 1, 4), df_prosp$`Outcome Measure`)

df_prosp_combined <- data.frame(Outcome_Measure = df_prosp$Outcome_Measure_Truncated)


outcome_counts <- table(df_prosp_combined$Outcome_Measure)


barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count")
```

```{r}

df_prosp$Cannabis_Level_Truncated <- ifelse(nchar(df_prosp$`Cannabis Level of use`) > 4, word(df_prosp$`Cannabis Level of use`, 1, 4), df_prosp$`Cannabis Level of use`)

df_prosp_combined_cannabis <- data.frame(Cannabis_Level = df_prosp$Cannabis_Level_Truncated)

cannabis_counts <- table(df_prosp_combined_cannabis$Cannabis_Level)


barplot(cannabis_counts, col = rainbow(length(cannabis_counts)), main = "Cannabis Level of Use Distribution", xlab = "Cannabis Level of Use", ylab = "Count", las = 2)


df_prosp$Outcome_Truncated <- ifelse(nchar(df_prosp$Outcome) > 4, word(df_prosp$Outcome, 1, 4), df_prosp$Outcome)


df_prosp_combined_outcome <- data.frame(Outcome = df_prosp$Outcome_Truncated)


outcome_counts <- table(df_prosp_combined_outcome$Outcome)


barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count", las = 2)
```

```{r}

df_prosp_cannabis <- data.frame(Cannabis_Level = df_prosp$`Cannabis Level of use`)


cannabis_counts <- table(df_prosp_cannabis$Cannabis_Level)

barplot(cannabis_counts, col = rainbow(length(cannabis_counts)), main = "Cannabis Level of use Distribution", xlab = "Cannabis Level of use", ylab = "Count", las = 2, cex.names = 0.7)


df_prosp_outcome <- data.frame(Outcome = df_prosp$Outcome)


outcome_counts <- table(df_prosp_outcome$Outcome)


barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Distribution", xlab = "Outcome", ylab = "Count", las = 2, cex.names = 0.7)


df_prosp_outcome_measure <- data.frame(Outcome_Measure = df_prosp$`Outcome Measure`)


outcome_measure_counts <- table(df_prosp_outcome_measure$Outcome_Measure)


barplot(outcome_measure_counts, col = rainbow(length(outcome_measure_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count", las = 2, cex.names = 0.7)







```

```{r}

options(repr.plot.width = 12, repr.plot.height = 16)


df_prosp_cannabis <- data.frame(Cannabis_Level = df_prosp$`Cannabis Level of use`)


cannabis_counts <- table(df_prosp_cannabis$Cannabis_Level)


barplot(cannabis_counts, col = rainbow(length(cannabis_counts)), main = "Cannabis Level of Use Distribution", xlab = "Cannabis Level of Use", ylab = "Count", las = 2, cex.names = 0.8)


df_prosp_outcome <- data.frame(Outcome = df_prosp$Outcome)


outcome_counts <- table(df_prosp_outcome$Outcome)


barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Distribution", xlab = "Outcome", ylab = "Count", las = 2, cex.names = 0.8)


df_prosp_outcome_measure <- data.frame(Outcome_Measure = df_prosp$`Outcome Measure`)


outcome_measure_counts <- table(df_prosp_outcome_measure$Outcome_Measure)


barplot(outcome_measure_counts, col = rainbow(length(outcome_measure_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count", las = 2, cex.names = 0.8)




```



```{r}

options(repr.plot.width = 12, repr.plot.height = 25)


df_prosp_cannabis <- data.frame(Cannabis_Level = df_prosp$`Cannabis Level of use`)


cannabis_counts <- table(df_prosp_cannabis$Cannabis_Level)


par(mar = c(10, 4, 4, 2) + 0.1)
barplot(cannabis_counts, col = rainbow(length(cannabis_counts)), main = "Cannabis Level of Use Distribution", xlab = "Cannabis Level of Use", ylab = "Count", las = 2, cex.names = 0.8)
text(barplot(cannabis_counts, col = rainbow(length(cannabis_counts)), main = "Cannabis Level of Use Distribution", xlab = "Cannabis Level of Use", ylab = "Count", las = 2, cex.names = 0.8), labels = names(cannabis_counts), xpd = TRUE, srt = 45, adj = c(1.1, 1.1))


df_prosp_outcome <- data.frame(Outcome = df_prosp$Outcome)


outcome_counts <- table(df_prosp_outcome$Outcome)


par(mar = c(10, 4, 4, 2) + 0.1)
barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Distribution", xlab = "Outcome", ylab = "Count", las = 2, cex.names = 0.8)
text(barplot(outcome_counts, col = rainbow(length(outcome_counts)), main = "Outcome Distribution", xlab = "Outcome", ylab = "Count", las = 2, cex.names = 0.8), labels = names(outcome_counts), xpd = TRUE, srt = 45, adj = c(1.1, 1.1))


df_prosp_outcome_measure <- data.frame(Outcome_Measure = df_prosp$`Outcome Measure`)


outcome_measure_counts <- table(df_prosp_outcome_measure$Outcome_Measure)


par(mar = c(10, 4, 4, 2) + 0.1)
barplot(outcome_measure_counts, col = rainbow(length(outcome_measure_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count", las = 2, cex.names = 0.8)
text(barplot(outcome_measure_counts, col = rainbow(length(outcome_measure_counts)), main = "Outcome Measure Distribution", xlab = "Outcome Measure", ylab = "Count", las = 2, cex.names = 0.8), labels = names(outcome_measure_counts), xpd = TRUE, srt = 45, adj = c(1.1, 1.1))


```








