---
title: "Studylist_Comparision"
author: "Johanna M Groening"
date: "2023-05-25"
output: html_document
---



```{r}
studylist_required<-clean_studylist_cohort$node_label
studylist_extracted<-all_merged_unique$Author
```

```{r}
print(nrow(clean_studylist_cohort))
```
```{r}
print(nrow(all_merged_unique))
```

```{r}
# Check if cells in all_merged$Author are included in clean_studylist_cohort
clean_studylist_cohort$extracted <- ifelse(clean_studylist_cohort$node_label %in% all_merged$Author, "Yes", "No")

# View the updated clean_studylist_cohort dataframe
print(clean_studylist_cohort)


```


```{r}
# Find cells that do not overlap between clean_studylist_cohort$Author and all_merged$Author
not_overlap <- setdiff(clean_studylist_cohort$node_label, all_merged$Author)

# Create a new vector with non-overlapping cells
tobe_extracted <- ifelse(clean_studylist_cohort$node_label %in% not_overlap, clean_studylist_cohort$node_label, NA)

# Remove the NA values from the new vector
tobe_extracted <- tobe_extracted[!is.na(tobe_extracted)]

# View the updated vector without NA values
print(tobe_extracted)
length(tobe_extracted)
```
```{r}
# Load the "openxlsx" package
library(openxlsx)

# Write tobe_extracted dataframe to an Excel file
write.xlsx(tobe_extracted, "studys_toextract.xlsx", rowNames = FALSE)

# Write clean_studylist_cohort dataframe to an Excel file
write.xlsx(clean_studylist_cohort, "new_studylist_cohort.xlsx", rowNames = FALSE)
```

```{r}
write.xlsx(clean_studylist_cohort, "new_studylist_cohort", rowNames = FALSE)
```



```{r}

# Create Excel file

library(openxlsx)
wb <- createWorkbook()

# Add data frames to separate sheets

addWorksheet(wb, "CHR_MA")
writeData(wb, "CHR_MA",CHR_Author_unique )
addWorksheet(wb, "CHR_Umbrella")
writeData(wb, "CHR_Umbrella",studylist_CHR_clean)


addWorksheet(wb, "HP_MA")
writeData(wb, "HP_MA", HP_Author_unique)
addWorksheet(wb, "HP_Umbrella")
writeData(wb, "HP_Umbrella", studylist_HP_clean)

addWorksheet(wb, "P_MA")
writeData(wb, "P_MA", P_Author_unique)
addWorksheet(wb, "P_Umbrella")
writeData(wb, "P_Umbrella", studylist_p_clean)

# Save the Excel file
saveWorkbook(wb, "HP_CHR_P.xlsx", overwrite = TRUE)

```


